# Health check
management.endpoint.health.probes.enabled: true
management.health.livenessState.enabled: true
management.health.readinessState.enabled: true

# Prometheus
management.endpoints.web.exposure.include: prometheus,health
management.metrics.tags:
  application: SixLetterWordsApi

# Management port
management:
  server:
    port: 8888
