openapi: 3.0.3
info:
  title: Six Letter Words API
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: word
    description: process words
paths:
  /word:
    post:
      tags:
        - word
      operationId: processWordFile
      summary: Searching for words within a file
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: File successfully processed
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WordResponseResource'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponseResource'
components:
  schemas:
    WordResponseResource:
      required:
        - result
        - parts
      type: object
      properties:
        result:
          type: string
          description: Word found within the file
          example: foobar
        parts:
          type: array
          items:
            type: string
          description: List of substrings used to construct the word
          example:
            - fo
            - bar
    ProblemDetailResponseResource:
      required:
        - title
        - status
        - detail
        - instance
      properties:
        title:
          type: string
          description: A short, human-readable summary of the problem type
          example: Empty file
        status:
          type: integer
          description: The HTTP status code generated by the origin server for this occurrence of the problem
          example: 400
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
          example: Empty file, please upload a valid file with text
        instance:
          type: string
          description: A URI reference that identifies the specific occurrence of the problem
          example: /word
